name: Example Workflow

on:
  push:
    branches:
      - main

env:
  ARTIFACT_NAME: myartifact

jobs:
  sharing-data:
    name: Sharing artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .