name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  sharing-data:
    name: Sharing artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - run: expr 1 + 1 > file.txt
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: file.txt