name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  job-linux:
    name: Linux Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Time
        run: echo "The current time on Linux is $(date +%T)"

  job-windows:
    name: Windows Job
    runs-on: windows-latest
    steps:
      - name: Print Time
        run: echo "The current time on Windows is $(powershell Get-Date -Format HH:mm:ss)"

  job-macos:
    name: macOS Job
    runs-on: macos-latest
    steps:
      - name: Print Time
        run: echo "The current time on macOS is $(date +%T)"

  dependent-job:
    name: Dependent Job
    runs-on: ubuntu-latest
    needs: [job-linux, job-windows, job-macos]
    steps:
      - name: Print Message
        run: echo "All three parallel jobs are complete!"
